image: node:20.3.1

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - echo "Starting build"
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  script:
    - echo "Deploying to Firebase"
    - npm install -g firebase-tools
    - firebase deploy --only hosting --token $FIREBASE_TOKEN
